services:
  - type: web
    name: pontia-mlops-tutorial-juan-martinez
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    rootDir: deployment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GITHUB_REPO
        value: jumarfradev/pontia-mlops-tutorial-juan-martinez
      - key: PYTHON_VERSION
        value: "3.10"
